sudo: false
language: node_js
addons:
  apt:
    packages:
      - ncurses-base
node_js:
  - 'stable'
  - '0.12'
  - '0.10'
  - '0.8'
before_install:
  - toe
  - npm install -g npm@2
script:
  - npm run travis
