name: CI

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 16
          - 14
          - 12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
